BLOCK_SIZE = 20
BLOCK_SIZE_TUPLE = (BLOCK_SIZE, BLOCK_SIZE)
WINDOW_SIZE = (
    BLOCK_SIZE * 25,
    BLOCK_SIZE * 25
)

FPS = 30
TIMEOUT = 4
SPEED = 0.5 - (0.1 * TIMEOUT)

LEFT = 'left'
RIGHT = 'right'
UP = 'up'
DOWN = 'down'
CLOSE = 'close'
